### ISSUE TITLE
关于文档的问题

### ISSUE THREAD

**Issue by Will-Liang** [linpeilie/mapstruct-plus#54]
网站首页的特性是一排3个，请问是如何设置的

**Comment by linpeilie** [comment]
https://github.com/linpeilie/mapstruct-plus/blob/main/docs/.vuepress/styles/index.scss 

这个文件中，添加的如下样式：

```css
// place your custom styles here
@media (min-width: 1440px) {
  .feature-item {
    flex-basis: calc(33% - 3rem);
    padding-top: 1.5rem;
    padding-bottom: 1.5rem;
  }
}
```
